# Tasks file for roles/ssh
---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ssh_dir }}"
    state: directory
    mode: '0700'

- name: Copy private key
  ansible.builtin.copy:
    src: ../ssh/proton_priv
    dest: "{{ ssh_dir }}/proton"
    mode: '0600'

- name: Copy public key
  ansible.builtin.copy:
    src: ../ssh/proton_pub
    dest: "{{ ssh_dir }}/proton.pub"
    mode: '0644'

- name: Add Config
  ansible.builtin.template:
    src: config.j2
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: '0600'
