---
- name: Setup SSH keys
  hosts: localhost
  vars:
    ssh_dir: "{{ ansible_env.HOME }}/.ssh"
  
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "{{ ssh_dir }}"
        state: directory
        mode: '0700'

    - name: Copy private key
      copy:
        src: ../ssh/proton_priv
        dest: "{{ ssh_dir }}/proton"
        mode: '0600'

    - name: Copy public key
      copy:
        src: ../ssh/proton_pub
        dest: "{{ ssh_dir }}/proton.pub"
        mode: '0644'

    - name: Add Config
      template:
        src: config.j2
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        mode: '0600'

    # - name: Set correct permissions on .ssh directory
    #   file:
    #     path: "{{ ssh_dir }}"
    #     state: directory
    #     recurse: yes
    #     mode: '0700'

